#!/bin/sh

LED=$1
SCENARIO=$2

if [ $LED != "cloud" ]; then
    exit 0
fi


# apply scenario
case "$SCENARIO" in
	on)
        ubus call led.status set '{"state":"ok"}'
		;;

	off)
        ubus call led.status set '{"state":"error"}'
		;;

	slow)
        ubus call led.status set '{"state":"notice"}'
		;;


	fast)
        ubus call led.status set '{"state":"alert"}'
		;;

	*)
		exit 1
		;;
esac

