#!/bin/sh


console_out()
{
    printf "\n\n$@\n\n" > /dev/console
}


case "$ACTION" in
    add|register)
    [ "dectshort" == "$INTERFACE" ] && {
        local claimed=$(jbus.ui cloud.claiming get_status 2> /dev/null)
        [ "$claimed" == "claimed" ] && {
            console_out "Start sensor registering"
            jbus.ui dect.registration start
        } || {
            console_out "Start claiming procedure"
            jbus.ui cloud.claiming start
        }
    }
    ;;
    remove|unregister)
    ;;
esac

