#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
STOP=09

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1


GIGA_DIR=${GIGA_DIR:-/usr/share/gigaset}

BIN_DIR=$GIGA_DIR/usr/bin
ETC_DIR=$GIGA_DIR/etc
DATA_DIR=/usr/gigaset/data



source $BIN_DIR/env.sh


start() {
    export PATH=$BIN_DIR:$PATH

    # Export variables set by env.sh
    export TFTP_DIR=$TFTP_DIR
    export DEVICE_ID=$DEVICE_ID
    export BAS_TAG=$BAS_TAG
    export BAS_HASH=$BAS_HASH
    export UA="Basestation/$BAS_TAG"

    # generate keypairs and csr if needed
    [[ -f $BIN_DIR/ssl_gen.sh ]] && $BIN_DIR/ssl_gen.sh

    # run pre reef script
    [[ -f $BIN_DIR/pre_reef.sh ]] && source $BIN_DIR/pre_reef.sh

    # remove tmp statuses
    rm -f /tmp/cfg/statuses

    # check databases
    /usr/bin/coin

    echo == REEF basestation is being started ...
    echo == REEF id   $DEVICE_ID
    echo == REEF tag  $BAS_TAG
    echo == REEF hash $BAS_HASH

    service_start /usr/bin/jbus
    sleep 1
    service_start /usr/bin/wdt  -s $BIN_DIR/wdt_reset.sh
    service_start /usr/bin/coco --ca $ETC_DIR/ssl/certs/ca-bundle.pem --key $DATA_DIR/cert/cert.key --cert $DATA_DIR/cert/cert.crt
    service_start /usr/bin/tram
    service_start /usr/bin/qpa
    service_start /usr/bin/tick
    service_start /usr/bin/uleapp -6 -c

    echo == REEF basestation ready

    # run post reef script
    [[ -f $BIN_DIR/post_reef.sh ]] && source $BIN_DIR/post_reef.sh
}


stop() {
    service_stop /usr/bin/tram
    service_stop /usr/bin/qpa
    service_stop /usr/bin/coco
    service_stop /usr/bin/tick
    service_stop /usr/bin/uleapp
    service_stop /usr/bin/wdt
    service_stop /usr/bin/jbus
}

